create table cliente (
	id_cliente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(60),
	cpf varchar(11),
	email varchar(50),
	data_nascimento date,
	PRIMARY KEY (id_cliente)
);

CREATE SEQUENCE documento_id_seq;
CREATE TABLE documento (
id_documento bigint PRIMARY KEY DEFAULT nextval('documento_id_seq'),
identidade varchar(15),
orgao_expeditor varchar(20),
cnh varchar(20),
titulo_eleitor varchar(15),
id_cliente bigint unique,
FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);
INSERT INTO documento (identidade, orgao_expeditor, cnh, titulo_eleitor, id_cliente)
VALUES ('098442','IFP','234343242','234243',1);
